# -*- coding: utf-8 -*-
"""EDAP7905.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZnn0qhik7XGgqaP2xKXgUAayEZsyuwc

#22November 2025 Oral Exam _ Valentina Oelofse 2020066672

#Import
"""

import sqlite3
import pandas as pd

#Link for the dataset chinook:https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite mentioned to use to the SQLITE
!wget -q https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite
conn = sqlite3.connect('Chinook_SqliteGit.sqlite')

"""#Question 1 Revenue by Country + share of total
Using invoice compute total revenue per bulling country. Calculate each country's percentage share of overall revenue
q1 = pd.read_sql("""
SELECT
  i.BillingCountry,
  SUM(i.Total) AS TotalRevenue,
  SUM(I.Total) / (SELECT SUM(Total) FROM Invoice)*100 AS RevenueSharePercent

FROM Invoice AS i

GROUP BY BillingCountry

ORDER BY TotalRevenue DESC;""",conn)
print(q1)

"""My insight: The top markets are the USA, Canada, France, Brazil and Germany. From which USA has a revenue share percentage of 22.46% and Canada 13.05%.

#Question 2 Top 10 artists by sales

"""##Q2 Answer"""

q2 = pd.read_sql("""
SELECT
  a.Name AS ArtistName,
  SUM(i.Total) AS TotalSales,
  SUM(IL.Quantity) AS TracksSold

FROM Artist as a

JOIN Album AS al ON a.ArtistId = al.ArtistId
JOIN Track AS t ON al.AlbumId = t.AlbumId
JOIN InvoiceLine AS IL ON t.TrackId = IL.TrackId
JOIN Invoice AS i ON IL.InvoiceId = i.InvoiceId

GROUP BY ArtistName

ORDER BY TotalSales DESC

LIMIT 10;""",conn)
print(q2)

"""My insight: The most popular artist is Iron Maiden taking the first position with the highest sales in terms of Money earned.
The second highest earning artist is U2.

#Question 3 Customer life time value + last purchase
For every customer compute the lifetime value = sum of all invoices, and the also the most recent purchase

"""##Q3 Answer"""

#Finalq3

q3 = pd.read_sql("""
SELECT
  c.CustomerId, c.FirstName||' '||c.LastName AS FullName, c.Country, SUM(i.Total) AS LifetimeValue, MAX(i.InvoiceDate) AS LastPurchaseDate

FROM Customer as c

JOIN Invoice AS i ON c.CustomerId = i.CustomerId

GROUP BY FullName

ORDER BY LifetimeValue DESC


;""",conn)
print(q3)

"""My insight: The highest paying customer is Helena Holý and the last date of purchase was 2025-11-13 meaning that the customer is still active. In contrast the second highest paying customer is Richard Cunningham yet the last date of purchas was 2025-04-05 which is not that recent.
